llm:
  provider: "bedrock"  # Options: bedrock, openai
  model_name: "anthropic.claude-3-5-sonnet-20241022-v2:0" 
  temperature: 0.7
  max_tokens: 4096
  region: "us-west-2"  # AWS region for Bedrock

tools:
  search:
    enabled: true
    max_results: 5
  web_browser:
    enabled: true
    timeout: 30

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 